[package]
name = "trie-hard"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rstest = "0.21.0"
criterion = "0.3"
radix_trie = "0.2.1"
paste = "1.0.15"
once_cell = "1.19.0"

[[bench]]
name = "bench"
harness = false

